#!/bin/bash

DOTFILES_REPO="https://github.com/jnormington/dotfiles"
DOTFILES=$HOME/.dotfiles

VUNDLE_DIR=$HOME/.vim/bundle/Vundle.vim
CONFIG_DIR=$HOME/.config
FONTS_DIR=$HOME/.local/fonts
SSH_DIR=$HOME/.ssh
FTPLUGIN_DIR=$HOME/.vim/after/ftplugin
USER_SYSTEMD_DIR=$HOME/.config/systemd/user
UDEV_RULES_DIR=/etc/udev/rules.d
SCRIPTS_DIR=$HOME/.local/bin

set -e

PACKAGES=(
  git
  vim
  dunst
  tmux
  xclip
  playerctl
  xorg-xbacklight
  dnsutils
  bash-completion
  bluez-utils
  bluez
  pulseaudio-bluetooth
  libcurl-gnutls # for spotify
)

mkdirAndSymlink() {
  mkdir -p $1

  if [ ! -e $1/$3 ];
  then
    ln -s $DOTFILES/$2 $1/$3
    echo "symlinked $DOTFILES/$2 -> $1/$3"
  else
    echo "skipped $2"
  fi
}

enableAndStartServices() {
  systemctl --user enable ssh-agent
  systemctl --user start ssh-agent
}

# Where I mount all external disks
echo "Create media dir"
mkdir -p $HOME/media

echo "Installing libs"
sudo pacman -S ${PACKAGES[@]}

if [ ! -d $VUNDLE_DIR ];
then
  echo "Installing Vundle"
  git clone https://github.com/VundleVim/Vundle.vim.git $VUNDLE_DIR
fi

echo "Installing dotfiles"

for conf in $(ls $DOTFILES)
do
  case "$conf" in
    fonts)
      if [ ! -d $FONTS_DIR ];
      then
        mkdir -p $FONTS_DIR
        ln -s $DOTFILES/fonts/* $FONTS_DIR
      else
        echo "skipped $conf"
      fi
      ;;
    ftplugin)
      if [ ! -d $FTPLUGIN_DIR ];
      then
        mkdir -p $FTPLUGIN_DIR
        ln -s $DOTFILES/ftplugin/* $FTPLUGIN_DIR
      else
        echo "skipped $conf"
      fi
      ;;
    scripts)
      if [ ! -d $SCRIPTS_DIR ];
      then
        mkdir -p $SCRIPTS_DIR
        ln -s $DOTFILES/scripts/* $SCRIPTS_DIR
      else
        echo "skipped $conf"
      fi
      ;;
    systemd)
      if [ ! -d $USER_SYSTEMD_DIR ];
      then
        mkdir -p $USER_SYSTEMD_DIR
        ln -s $DOTFILES/systemd/user/* $USER_SYSTEMD_DIR
      else
        echo "skipped $conf"
      fi
      ;;
    udev)
      echo "copying udev rules"
      sudo cp $DOTFILES/udev/* $UDEV_RULES_DIR/
      ;;
    ssh_config)
      mkdirAndSymlink $SSH_DIR $conf config
      ;;
    i3status)
      mkdirAndSymlink $HOME/.config/$conf $conf config
      ;;
    i3config)
      mkdirAndSymlink $HOME/.config/i3 $conf config
      ;;
    gitconfig|gitignore_global|vimrc|tmux.conf)
      mkdirAndSymlink $HOME $conf .$conf
      ;;
    dir_colors|bashrc|bash_aliases|profile|xinitrc|Xdefaults)
      mkdirAndSymlink $HOME $conf .$conf
      ;;
    dunstrc)
      mkdirAndSymlink $HOME/.config/dunst $conf $conf
      ;;

  esac
done

echo "Starting services"
enableAndStartServices

echo "Reload udev rules"
sudo udevadm control --reload-rules

echo "Running commands in vim"
vim +PluginInstall +qall +GoInstallBinaries
