#!/usr/bin/env sh

yabai -m config external_bar all:25:0

# bar settings
yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child

# floating windows are always on top
yabai -m config window_topmost               on

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app='Calculator' manage=off
