after-login-command = []
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpace restart
    'exec-and-forget borders active_color=0xffff4641‰ width=5.0',
    'exec-and-forget /usr/local/bin/brew services restart sketchybar'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
  '/Users/jon/.config/sketchybar/plugins/aerospace.sh'
]

start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 20

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Possible values: (qwerty|dvorak)
key-mapping.preset = 'qwerty'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 3
inner.vertical =   3
outer.left =       3
outer.bottom =     3
outer.top =        33
outer.right =      3

[mode.main.binding]
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# App shortcuts
ctrl-enter = 'exec-and-forget open -n /Applications/Alacritty.app'
ctrl-alt-f = 'exec-and-forget open -n /Applications/Firefox.app'
ctrl-alt-g = 'exec-and-forget open -n /Applications/TablePlus.app'

# layout setup
alt-q = 'layout accordion'
alt-w = 'layout h_tiles'
alt-e = 'layout v_tiles'
alt-shift-f = 'fullscreen'
alt-shift-space = 'layout floating tiling'

# focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# move window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# join/split window
alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

# workspaces
alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'
alt-shift-6 = 'workspace 6'

alt-tab = 'workspace-back-and-forth'

# move to workspace
cmd-shift-1 = 'move-node-to-workspace 1'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-shift-3 = 'move-node-to-workspace 3'
cmd-shift-4 = 'move-node-to-workspace 4'
cmd-shift-5 = 'move-node-to-workspace 5'
cmd-shift-6 = 'move-node-to-workspace 6'

# Resize mode

alt-r = 'mode resize'

[mode.resize.binding]
  h = 'resize width -50'
  j = 'resize height +50'
  k = 'resize height -50'
  l = 'resize width +50'
  enter = 'mode main'
  esc = 'mode main'

alt-shift-r = 'reload-config'
