#!/bin/bash

INT_1="eDP1"
EXT_1="DP1"
EXT_2="DP2"

DP1=$(xrandr | grep "^$EXT_1" | cut -d ' ' -f2)
DP2=$(xrandr | grep "^$EXT_2" | cut -d ' ' -f2)

X_OPTS=""
ARG="${1:-external}"

notify_user() {
  notify-send -u low -t 2000 "$1"
}

disconnect_monitor() {
  xrandr --output $INT_1 --mode 1920x1080
  xrandr --output $EXT_1 --off
  xrandr --output $EXT_2 --off
}

if [[ -z "$ARG" ]];
then
  disconnect_monitor
  notify_user "Reset monitor setup"
  exit 0
fi

case $ARG in
"extend")
  X_OPTS="--left-of $INT_1"
  ;;
"mirror")
  X_OPTS="--same-as $INT_1"
  ;;
"external")
  X_OPTS="--output $INT_1 --off"
  ;;
"present")
  X_OPTS="--output $INT_1 --off --output $EXT_1 --mode 1920x1080"
  ;;
*)
  X_OPTS=""
  ;;
esac

if [[ "$DP1" == "disconnected" || "$DP2" == "disconnected" ]];
then
  disconnect_monitor
fi

if [[ "$DP1" == "connected" ]];
then
  xrandr --output $EXT_1 --auto $X_OPTS
  notify_user "External display connected"
fi

if [[ "$DP2" == "connected" ]];
then
  xrandr --output $EXT_2 --auto $X_OPTS
  notify_user "External display connected"
fi
